CREATE TABLE Usuario(
	id INT NOT NULL IDENTITY,
	nome VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL,
	senha VARCHAR(100) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE Telefone(
	id INT NOT NULL IDENTITY,
	idUsuario INT NOT NULL,
	ddd INT,
	numero VARCHAR(30),
	tipo VARCHAR(30),
	PRIMARY KEY(id),
	FOREIGN KEY(idUsuario) REFERENCES USUARIO (ID)
);